# Generated by Django 3.2.6 on 2021-08-15 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creatorplatform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stores',
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='creatorplatform.store', verbose_name='Stores'),
        ),
    ]
